services:

  app:
    image: ghcr.io/jaikhlang/careerpulse:latest
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
