services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: careerpulse-app

    volumes:
      - .:/var/www/html

    depends_on:
      - postgres
      - redis

    networks:
      - careerpulse

  nginx:
    image: nginx:latest

    container_name: careerpulse-nginx

    ports:
      - '8000:80'

    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

    networks:
      - careerpulse

  postgres:
    image: postgres:17

    container_name: careerpulse-postgres

    environment:
      POSTGRES_DB: careerpulse
      POSTGRES_USER: careerpulse
      POSTGRES_PASSWORD: careerpulse

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - careerpulse

  redis:
    image: redis:8-alpine

    container_name: careerpulse-redis

    ports:
      - '6379:6379'

    volumes:
      - redis_data:/data

    networks:
      - careerpulse

  mailpit:
    image: axllent/mailpit

    container_name: careerpulse-mailpit

    ports:
      - '1025:1025'
      - '8025:8025'

    networks:
      - careerpulse

volumes:
  postgres_data:
  redis_data:

networks:
  careerpulse:
